### ISSUE TITLE
Landing page Logo has wrong redirect

### ISSUE THREAD

**Issue by InterCroneworld** [InterCroneworldOrg/intercroneswap-interface#136]
**Describe the bug**
When clicking on the ISwap Logo on landing page, it should go to /#/ route instead of /#/home.

**To Reproduce**
1. Go to ww.intercroneswap.com
2. Click on the ISwap logo on the topleft corner
3. It goes to wrong location

**Expected behavior**
It should redirect to the landing page

**Screenshots**
<img width="1020" alt="Screenshot 2022-04-14 at 15 28 10" src="https://user-images.githubusercontent.com/86061927/163401340-d3fc1c03-3ab7-4f54-9369-5308df3a9f4a.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by Manntrix** [comment]
1. Landing page link redirect fixed.
