### ISSUE TITLE
Staking

### ISSUE THREAD

**Issue by InterCroneworld** [InterCroneworldOrg/intercroneswap-interface#139]
**Describe the bug**
Improve the process of stake and unstake

**To Reproduce**
1. Go to 'https://trx.intercroneswap.com/#/stake'
2. Click on 'Stake'
3. a new window open. 

**Expected behavior**
1. user want to stake the LP and first he see this. 

![image](https://user-images.githubusercontent.com/86061927/163544170-203adf3e-6639-46d1-a34e-9f3484599c6b.png)

2. i see first 2 buttons approve and deposit. this need to be only one. first it is approve. if the approve is finish it swithc to deposit
![image](https://user-images.githubusercontent.com/86061927/163544339-c00577c7-dce2-4b28-9cd8-ac57ccfc0eff.png)

3. i press now deposit. i see a short time a new windw but than everything is like before. 
![image](https://user-images.githubusercontent.com/86061927/163544461-a639b138-a69a-4723-be88-9b732df2db7e.png)
we need here also a confirmation picture. 

![image](https://user-images.githubusercontent.com/86061927/163544539-c1241b72-3b12-4fc9-b18e-a0641581b3c8.png)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Monahawk** [comment]
Fixed by #141
