### ISSUE TITLE
Exchange Page update

### ISSUE THREAD

**Issue by Bludigitanos** [InterCroneworldOrg/intercroneswap-interface#167]
please put the settings from the header to the place like in the design:

![image](https://user-images.githubusercontent.com/103650709/165148723-bf221384-35a2-432f-830e-c62fd2d0e04e.png)

delete the  exchange/liquidity buttons
<img width="287" alt="image" src="https://user-images.githubusercontent.com/103650709/165148897-371700b5-aa47-48af-94be-6b611ac9a5ec.png">

new design:
![image](https://user-images.githubusercontent.com/103650709/165148956-545c2ec6-986f-443f-b126-afa75b671281.png)

**Comment by Monahawk** [comment]
Partially updated by #193 
To be decided regarding advanced settings
