### ISSUE TITLE
window should close after Harvest

### ISSUE THREAD

**Issue by InterCroneworld** [InterCroneworldOrg/intercroneswap-interface#171]
the steps. 

1. i make the harvest 
![image](https://user-images.githubusercontent.com/86061927/165456950-821d5540-90d2-4ce1-908b-a2f12310306c.png)

2. i see this and can press close
![image](https://user-images.githubusercontent.com/86061927/165457016-162ea551-7ed0-4dee-9f95-ad96fe24c53b.png)

3. i want to make now a secound harvest. my transaction is finish but i get again this popup
![image](https://user-images.githubusercontent.com/86061927/165457157-3b71539e-6aef-4b58-978c-6cdd599b04d2.png)

i need to refresh the page to be able to make a new harvest.

**Comment by Monahawk** [comment]
Fixed and rolled out with #172
