### ISSUE TITLE
missing link and missing 404 page. 

### ISSUE THREAD

**Issue by InterCroneworld** [InterCroneworldOrg/intercroneswap-interface#174]
on https://trx.intercroneswap.com/#/stake when you stake and unstake the get LP come to the 404 page. 

also the 404 page should be updated with the figma design. 

![image](https://user-images.githubusercontent.com/86061927/165696311-2a226d10-bb0d-4c04-a2f0-2c1f6bc4b280.png)

![image](https://user-images.githubusercontent.com/86061927/165696116-79de5fe3-30d1-4cb4-a9e3-3802dfdbe8f6.png)

**Comment by Monahawk** [comment]
is fixed by #182
