### ISSUE TITLE
Stake approve call dont create a Transaction Submitted

### ISSUE THREAD

**Issue by InterCroneworld** [InterCroneworldOrg/intercroneswap-interface#175]
after the approve call i dont see a message like after the staking. 

![image](https://user-images.githubusercontent.com/86061927/165696722-efc3e395-f7cf-489a-a9e9-5a017a657e82.png)
this should be also after the approve call. 

![image](https://user-images.githubusercontent.com/86061927/165696906-aae6a6ae-df89-49ee-9a8d-2cc8d61c7233.png)

**Comment by Monahawk** [comment]
Fixed, so that it doesn't create a transaction submitted, but shows an approving buttun until the stake contract gets approved. #182
