### ISSUE TITLE
update balance with max amount when press the value

### ISSUE THREAD

**Issue by InterCroneworld** [InterCroneworldOrg/intercroneswap-interface#186]
When i press the value on TRX it add 0 
![image](https://user-images.githubusercontent.com/86061927/166673085-4ece5c6b-17bd-4cba-99a1-77274b3df7b9.png)

for all other coins it add the token value

![image](https://user-images.githubusercontent.com/86061927/166673138-5a9b641e-62f3-4bbe-b60d-906f1755219f.png)

**Comment by Monahawk** [comment]
Fixed by #193
