### ISSUE TITLE
Add ICR to metamaks with logo

### ISSUE THREAD

**Issue by InterCroneworld** [InterCroneworldOrg/intercroneswap-interface#195]
![image](https://user-images.githubusercontent.com/86061927/169249687-b1c0b2c8-13e7-4ef5-ae02-62dcec43821e.png)
When i add ICR form the btt-bridge it add also the logo in metamask

https://wallet.bt.io/bridge

**Comment by Monahawk** [comment]
Fixed on bsc and btt
