### ISSUE TITLE
The connect button not support

### ISSUE THREAD

**Issue by SoraKohaku** [InterCroneworldOrg/intercroneswap-interface#299]
Connect button for the metamask or bnb not work. need support mobile model for that. It's said wrong provider.

**Comment by InterCroneworld** [comment]
for me it works fine. if you want to check the code please use the branch for each chain. 
https://github.com/InterCroneworldOrg/intercroneswap-bsc

**Comment by SoraKohaku** [comment]
Not more design like trust wallet etc? This good one. But we need more connector.
